version: "3.8"

services:
  masterprint-erp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: masterprint-erp
    restart: always
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./prisma/dev.db:/app/prisma/dev.db
      - ./public/uploads:/app/public/uploads
