version: '3.8'

services:
  masterprint-erp:
    build: .
    container_name: masterprint_erp
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=3000
      - NODE_ENV=production
